/**
 * Preset destination suggestions for the tour/hotel admin forms.
 * Combines Thailand's 77 provinces with well-known tourist cities/islands
 * that are not provinces themselves (e.g. Pattaya, Hua Hin, Koh Samui).
 * Used to seed the Destination datalist; DB values are merged on top so any
 * custom destination already saved still appears.
 */

// 77 provinces of Thailand (English spelling)
export const THAI_PROVINCES = [
  "Amnat Charoen",
  "Ang Thong",
  "Bangkok",
  "Bueng Kan",
  "Buriram",
  "Chachoengsao",
  "Chai Nat",
  "Chaiyaphum",
  "Chanthaburi",
  "Chiang Mai",
  "Chiang Rai",
  "Chonburi",
  "Chumphon",
  "Kalasin",
  "Kamphaeng Phet",
  "Kanchanaburi",
  "Khon Kaen",
  "Krabi",
  "Lampang",
  "Lamphun",
  "Loei",
  "Lopburi",
  "Mae Hong Son",
  "Maha Sarakham",
  "Mukdahan",
  "Nakhon Nayok",
  "Nakhon Pathom",
  "Nakhon Phanom",
  "Nakhon Ratchasima",
  "Nakhon Sawan",
  "Nakhon Si Thammarat",
  "Nan",
  "Narathiwat",
  "Nong Bua Lamphu",
  "Nong Khai",
  "Nonthaburi",
  "Pathum Thani",
  "Pattani",
  "Phang Nga",
  "Phatthalung",
  "Phayao",
  "Phetchabun",
  "Phetchaburi",
  "Phichit",
  "Phitsanulok",
  "Phra Nakhon Si Ayutthaya",
  "Phrae",
  "Phuket",
  "Prachinburi",
  "Prachuap Khiri Khan",
  "Ranong",
  "Ratchaburi",
  "Rayong",
  "Roi Et",
  "Sa Kaeo",
  "Sakon Nakhon",
  "Samut Prakan",
  "Samut Sakhon",
  "Samut Songkhram",
  "Saraburi",
  "Satun",
  "Sing Buri",
  "Sisaket",
  "Songkhla",
  "Sukhothai",
  "Suphan Buri",
  "Surat Thani",
  "Surin",
  "Tak",
  "Trang",
  "Trat",
  "Ubon Ratchathani",
  "Udon Thani",
  "Uthai Thani",
  "Uttaradit",
  "Yala",
  "Yasothon",
];

// Popular tourist cities / islands that are not provinces on their own
export const THAI_CITIES = [
  "Pattaya",
  "Hua Hin",
  "Hat Yai",
  "Ao Nang",
  "Railay",
  "Khao Lak",
  "Khao Sok",
  "Pai",
  "Koh Samui",
  "Koh Phangan",
  "Koh Tao",
  "Koh Lanta",
  "Koh Chang",
  "Koh Phi Phi",
  "Koh Lipe",
  "Koh Yao",
  "Similan Islands",
  "Phi Phi Islands",
];

// Sorted, de-duplicated preset list.
export const THAI_DESTINATIONS = [...THAI_PROVINCES, ...THAI_CITIES].sort((a, b) =>
  a.localeCompare(b)
);
