-- Seed: sample shows (Carnival Magic, Phuket FantaSea)
-- Run AFTER 008_create_shows_table.sql
-- Image fields left NULL — admin will upload images via the admin panel.

INSERT INTO `shows` (
  `name`, `slug`, `destination`, `venue`,
  `description`, `short_description`,
  `duration_days`, `duration_nights`, `duration_label`,
  `adult_price`, `child_price`, `currency`,
  `rating`, `review_count`, `is_featured`, `is_active`,
  `max_participants`, `min_participants`,
  `main_image`, `gallery_images`,
  `highlights`, `included`, `not_included`,
  `show_times`, `seat_zones`,
  `pickup_time`, `pickup_location`,
  `dropoff_time`, `dropoff_location`,
  `meal_info`, `transfer_info`,
  `what_to_bring`, `important_notes`,
  `terms_conditions`, `cancellation_policy`
) VALUES
(
  'Carnival Magic',
  'carnival-magic',
  'Phuket, Thailand',
  'Carnival Magic Park, Kamala, Phuket',
  'A spectacular 40-acre nighttime carnival theme park in Kamala, Phuket. Experience the grand "River Carnival" parade at the River Palace — one of the largest indoor show theatres in the world (16,000 sqm) — along with the Kingdom of Lights, the Carnival Fun Fair zone, festive shopping streets, and dazzling all-night entertainment.',
  'Nighttime carnival park with grand parade & Kingdom of Lights',
  1, 0, 'Evening Experience',
  2000.00, 1500.00, 'THB',
  4.7, 0, 1, 1,
  NULL, 1,
  NULL, NULL,
  '["Grand River Carnival parade","Kingdom of Lights","Carnival Fun Fair zone","Festive shopping street","All-night entertainment"]',
  '["Park entrance ticket","River Carnival parade (standard seat)","Kingdom of Lights access","Carnival zone activities"]',
  '["Hotel transfers (unless add-on selected)","International buffet dinner (unless add-on selected)","Royal Seat upgrade","Personal expenses","Gratuities"]',
  '["18:30","20:30"]',
  '[{"name":"Standard Seat","price":2000,"capacity":0},{"name":"Royal Seat","price":2500,"capacity":0}]',
  '17:00', 'Hotel lobby (Phuket pickup zones)',
  '23:00', 'Same as pickup',
  'Optional international buffet dinner add-on (+400 THB)',
  'Optional round-trip hotel transfer add-on',
  '["Comfortable walking shoes","Light jacket (theatre is air-conditioned)","Camera"]',
  'Park operates Monday, Wednesday, and Saturday from 17:30 to 23:30. Photography inside the show theatre is prohibited. Seat assignment is by computerized allocation on the day of visit.',
  'Tickets are non-transferable and valid only for the selected date. Outside food and beverages are not permitted inside the park.',
  'Free cancellation up to 48 hours before the visit date. No refund for cancellations within 48 hours.'
),
(
  'Phuket FantaSea',
  'phuket-fantasea',
  'Phuket, Thailand',
  'Palace of the Elephants, Kamala Beach, Phuket',
  'The award-winning "Fantasy of a Kingdom" cultural show at Phuket FantaSea — a 70-minute spectacle of Thai mythology, magic, acrobatics, and trained elephants performed inside the 3,000-seat Palace of the Elephants, designed to resemble a majestic Sukhothai-era palace. The cultural theme park also features carnival games, shopping village, and an optional Suriyamas seafood buffet.',
  'Award-winning Thai cultural show with elephants & acrobatics',
  1, 0, 'Evening Experience',
  1800.00, 1400.00, 'THB',
  4.8, 0, 1, 1,
  3000, 1,
  NULL, NULL,
  '["Fantasy of a Kingdom show (70 min)","Trained elephant performance","Thai mythology & acrobatics","Cultural theme park","Suriyamas seafood buffet (optional)"]',
  '["Theme park entrance","Fantasy of a Kingdom show ticket (standard seat)","Access to cultural village & carnival games"]',
  '["Hotel transfers (unless add-on selected)","Seafood buffet (unless add-on selected)","Gold Seat upgrade","Personal expenses","Gratuities"]',
  '["21:00"]',
  '[{"name":"Standard Seat","price":1800,"capacity":2700},{"name":"Gold Seat","price":2150,"capacity":300}]',
  '17:30', 'Hotel lobby (Phuket pickup zones)',
  '23:30', 'Same as pickup',
  'Optional Suriyamas seafood buffet add-on (Gold upgrade includes buffet + Gold Seat)',
  'Optional round-trip hotel transfer add-on',
  '["Comfortable clothing","Light jacket (theatre is air-conditioned)","Camera (outside theatre only)"]',
  'Park operates Tuesday, Friday, and Sunday from 17:30 to 23:30. Theatre gates open at 20:20; show starts at 21:00. Photography and recording are strictly prohibited inside the show theatre. Gold Seat must be paired with the buffet package.',
  'Tickets are non-transferable and valid only for the selected date. Late arrivals may not be admitted to the theatre.',
  'Free cancellation up to 48 hours before the visit date. No refund for cancellations within 48 hours.'
);
